theme: jekyll-theme-chirpy

baseurl: ""

lang: pt-BR

timezone: America/Sao_Paulo

title: demap.

tagline: Reviews de músicas

description: >-
  DEMAP é um blog para compartilhar minhas reviews de músicas.

url: ""

github:
  username: demapmusbr

twitter:
  username: demapmusbr

social:
  name: DEMAP
  email: contato@demap.mus.br
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/demapmusbr # change to your twitter homepage
    - https://github.com/demapmusbr # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

google_site_verification:

google_analytics:
  id:
  pv:
    proxy_endpoint:
    cache_path:

theme_mode: # [light|dark]

img_cdn: https://raw.githubusercontent.com/demapmusbr/cdn/refs/heads/main/logos/

avatar: logo.png

toc: true

comments:
  active:
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    input_position:
    lang:
    reactions_enabled:

assets:
  self_host:
    enabled: true
    env: [production]

pwa:
  enabled: true

paginate: 10

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - rollup.config.js
  - node_modules
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
